// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yevqrxpamqamutnexrpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlldnFyeHBhbXFhbXV0bmV4cnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjE1MDUsImV4cCI6MjA3MzU5NzUwNX0.bkenmCmZmhWx3LnuAVmgIMJW0s73jCk7upfmSGyvMTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});