// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsafurylczwyjqhekyhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzYWZ1cnlsY3p3eWpxaGVreWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDY5OTMsImV4cCI6MjA3MzYyMjk5M30.RkksrsiccK0DFMAvVud7U62AMmOIRdCXohjOIhX3xJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});